### ISSUE TITLE
Подклассы БУО

### ISSUE THREAD

**Issue by KennieSerg** [JustMarfix/VeryUsualDay#17]
- [ ] Админ-Команда "buo sergant ID"
- [ ] Админ-Команда "buo jagger ID"
- [ ] Админ-Команда "buo terminator ID"

Команды, которые работают на игроков, являющихся бойцом БУО

**buo sergant ID**
Характеристики
```
athp: 500
cinfo: [Сержант БУО]
```
Инвентарь
```
как у обычного БУО, но:
- вместо дробовика - MTF-E11-SR
- Рация
- патроны 5x56 (100)
```

**buo jagger ID**
Характеристики
```
athp: 600
cinfo: [Джаггернаут БУО]
```
Инвентарь
```
как у обычного БУО, но:
- вместо дробовика - Logicer
- патроны 7x62 (200)
```

**buo terminator ID**
Характеристики
```
athp: 1000
cinfo: [Ликвидатор БУО]
```
Инвентарь
```
- Combat Armor
- Painkillers
- Painkillers
- FR-MG-0
- Adrenaline
- MTF Operative Keycard
- SCP-500
- патроны 5x56 (120)
```
Эффекты
```
- BodyShot & Damage Reduction: 50
- Vitality
```

**Comment by JustMarfix** [comment]
Реализовано в виде шансов у `spawnbuo`.
