### ISSUE TITLE
SCP-076-2 Rework

### ISSUE THREAD

**Issue by KennieSerg** [JustMarfix/VeryUsualDay#35]
- [x] Ребаланс 076-2
- [x] Регенерация

**Ребаланс**
HP: 15000 >>> 9500
BodyShot&DamageReduction: 65 >>> 75

**Регенерация**
За нанесение урона (1 удар Jailbird) получит 25 HP с шансом 40%

**Comment by JustMarfix** [comment]
@KennieSerg по поводу фикса jailbird, не думаю, что это действительно нужно. Когда я последний раз играл за 076-2, всё работало, а значит скорее всего проблема ошибки в выдаче jailbird заключается в маленьком TPS.

**Comment by KennieSerg** [comment]
хорошо, фикс убираю тогда
