### ISSUE TITLE
Чистка инвентаря после смерти

### ISSUE THREAD

**Issue by KennieSerg** [JustMarfix/VeryUsualDay#61]
- Очищать все вещи человека при смерти/кике/отключении, если стоит ЗК/ИК

**Comment by JustMarfix** [comment]
@KennieSerg ты имеешь в виду, чтобы они не выпадали?

**Comment by KennieSerg** [comment]
@JustMarfix да, чтобы вещи не падали с трупов в Зелёный и Изумрудный Код. Если невозможно, то пусть конкретно эти вещи просто сразу очищаются, не затрагивая такие же вещи, которые не относились к инвентарю человека
