### ISSUE TITLE
SCP-019 spawn command

### ISSUE THREAD

**Issue by koldun212** [JustMarfix/VeryUsualDay#76]
- [x] вернуть SCP-008
- [x] команда на спавн SCP-019
вид команды: 
spawnscp019 (спавнит первый вид аномалии) 
spawnscp0192 (спавнит второй вид аномалии)
Возможен спавн нескольких особей одновременно одной командой
Далее будут показаны характеристики каждого вида

size: 0.6 0.6 0.6
athp от 500 до 1700 (рандом)
cinfo:  `<b><color=#960018>SCP-019-2</color></b>`
setname: Объект
класс: 049-2

size: 0.6 0.6 0.6
HP: от 100 до 600 (рандом)
cinfo:  `<b><color=#960018>SCP-019-2</color></b>`
effect: disabled
setname: Объект
класс: 939

**Comment by koldun212** [comment]
также, ты вроде можешь сделать спавн ровно в вазе, верно?

**Comment by JustMarfix** [comment]
> также, ты вроде можешь сделать спавн ровно в вазе, верно?

ага
